### ISSUE TITLE
Compile step does not use all cores... need to debug

### ISSUE THREAD

**Issue by graysky2** [dell/dkms#100]
When I inspect the output from `htop` while building, I see gcc using only 1 of 4 cores.  Is there a debug/logging mode I can manually invoke to verify?

**Comment by yuzaipiaofei** [comment]
you can build your codes with make -jN to verify the building time, it can be compared to the dkms build
@graysky2

**Comment by graysky2** [comment]
This is the nvidia-340xx driver on an old machine.  I will update this when I get a chance to do it.  I am unsure what the result will tell us.  When dkms builds, it only uses 1 of 4 cores (htop verified).  I am unsure what the time result will tell us that we don't already know.

**Comment by GoPerry** [comment]
add those to your dkms.conf ,then you will use the dual cpu to build it.
if you have no more question about this . 
 i will close the issue ,feel free to reopen it.


# Find out how many CPU cores can be use if we pass appropriate -j option to make.
# DKMS could use all cores on multicore systems to build the kernel module.
num_cpu_cores()
{
        if [ -x /usr/bin/nproc ]; then
                nproc
        else
                echo "1"
        fi
}

MAKE[0]="make -j$(num_cpu_cores) kdir=$kernel_source_dir -C $kernel_source_dir M=$dkms_tree/$module/$module_version/build"

~                                                                                                         
~
