### ISSUE TITLE
a problem of dkms

### ISSUE THREAD

**Issue by GitSoftwareNow** [dell/dkms#123]
when I run the robox scripts ,it reports that DKMS source tree has contained anbox-linux-1
I tried run dkms remove -m anbox-linux -v 1 --all and run robox again but it reports that DKMS source tree has contained anbox-linux-1 still on my system

**Comment by GoPerry** [comment]
@GitSoftwareNow 
If you still have the problem.
Could you show the dkms status and dkms remove output here.

**Comment by GoPerry** [comment]
feel free to reopen the issue when you have dkms remove and dkms status output and attach the make.log
