### ISSUE TITLE
Make is not a dependency of dkms package in CentOS 8

### ISSUE THREAD

**Issue by SolarGranola** [dell/dkms#128]
Saw this in version 2.8 on a fresh CentOS 8 image.
Make is not a dependency of the dkms package in CentOS. This manifested as an issue for us when we started supporting CentOS 8 for our installers. 

Previously, on a clean CentOS 7 system, we could pull down the dkms package and our installer using DKMS would build. Now, on a clean CentOS 8 system, pulling down dkms is not enough. DKMS uses make to build the kernel modules, seems like it should be a dependency...

Looking at the changelog for this coderepo I noticed this: 
![image](https://user-images.githubusercontent.com/8878506/82620666-f1582080-9b8d-11ea-9d7c-1539fb4744d6.png)
And make isn't listed as a dependency in CentOS 7 (using yum deplist dkms).
So maybe it's intentional but the dependency is now necessary?

**Comment by scaronni** [comment]
Hi, I'm the maintainer in Fedora/EPEL, I will look into it.

**Comment by scaronni** [comment]
Update is pending here, replacing the previous 2.8.2 and 2.8.3 ones: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-2a4c2c399e
