### ISSUE TITLE
Compile order (Feature Request)

### ISSUE THREAD

**Issue by ShaunPCcom** [dell/dkms#13]
Though I realise this may be unusual to be required, I was hoping that a compile order could be implemented. I have been running ZFS on Linux using Arch Linux and have found that the two modules required for ZFS to work have a compile order dependency. If DKMS installs the ZFS module before the SPL module the ZFS module will fail to install. It then becomes necessary to trigger the ZFS module install again the first attempt has completed and the remake the kernel images. I have found that over several kernel updates I have had several times where the compile order is okay and others where it is not. All works fine as long as SPL is installed before ZFS by DKMS. I am requesting that a feature be added to allow for module dependencies or at the very least be able to specify in a config file any modules that you wish to have compiled in a specific order. If this is already a feature, could you please tell me how to configure it. Thanks.

**Comment by happyaron** [comment]
commit 62b55cb034cbd5dceaeff43a7cfc6fdcda5b3681 should have your needs covered already.
