### ISSUE TITLE
Debian build depends on module-init-tools

### ISSUE THREAD

**Issue by karora** [dell/dkms#138]
In Debian module-init-tools was replaced by kmod.  Jessie has a module-init-tools dummy package which depends on kmod, but subsequent Debian releases don't have this.

The dependency in the `debian/control` file should be changed to:
```
Depends: ${misc:Depends},
 kmod | module-init-tools,
 gcc,
 make | build-essential | dpkg-dev,
 coreutils (>= 7.4),
 patch
```

**Comment by scaronni** [comment]
https://github.com/dell/dkms/commit/6283f80f7ab21b07fc37c70fec69180883e6ebb1
