### ISSUE TITLE
apt repository for Bionic beaver has very old DKMS version

### ISSUE THREAD

**Issue by LeKristapino** [dell/dkms#155]
Hi,

Is it possible to update DKMS in apt repository for Bionic beaver version of ubuntu? I can't seem to find newer versions of DKMS other than 2.2.1.0. For now we get a warning from one library

>We have detected dkms 2.2.1.0, we recommend using dkms version 2.4
or later for a better experience.
Please see the following reference about a removal issue in dkms pre-2.4:
https://github.com/dell/dkms/issues/37

But can't seem to update DKMS version, because it is not available (I also haven't been able to find .deb files with a newer version)

**Comment by scaronni** [comment]
Hi, if you're referring to the official Ubuntu repository, you need to ask the Ubuntu maintainers. Those are the people that package software and push updated packages for Ubuntu. This github is just for the open source project.
