### ISSUE TITLE
where is --no-clean-kernel --no-prepare-kernel    options  ?

### ISSUE THREAD

**Issue by limbo127** [dell/dkms#176]
Hello, 
since dkms 3.0.1 no more options, how can we do to have the same comportement
Regards 
Nicolas

**Comment by scaronni** [comment]
Hello, can you paste a link or something about your DKMS file? Thanks.

**Comment by limbo127** [comment]
hello,
this is from a arch linux standard installation   of virtualbox module
before yesterday ( with dkms arch) this command pass without issue, now
after upgrade dkms to 3.0.1 , not

yes |pacman -Syyu  virtualbox-host-dkms    # install dkms packages
# some var
VBOX=$(pacman -Q --info  virtualbox-host-dkms -q -e |grep Version|awk
'{print $3}'|sed 's/-.*//g')
VBOXHOST="${VBOX}_OSE"
# rebuild
dkms build -m vboxhost -v $VBOXHOST -k $KVER  --kernelsourcedir=$KDIR
--no-clean-kernel --no-prepare-kernel

Le mar. 16 nov. 2021 à 15:45, Simone Caronni ***@***.***> a
écrit :

**Comment by scaronni** [comment]
Those are deprecated, you can just remove them. I will add them here so you will get a warning: https://github.com/dell/dkms/commit/fff3032e5d471e3a1f456ec8fa1b20002024eb30

**Comment by scaronni** [comment]
https://github.com/dell/dkms/commit/3eb09af9358a1bd55b9ca04866b5161e714bd5f2.patch
