### ISSUE TITLE
dkms.service systemd run target issue (vmware modules/vmware.service)

### ISSUE THREAD

**Issue by feuler** [dell/dkms#19]
Hi.

i've  build a vmware modules dkms rpm for SUSE

But dkms.service here and on software.opensuse.com have "[Install] WantedBy=multi-user.target" and  opensuse sources also have "[Unit] Before=display-manager.service".

Problem is that vmware workstation 12.5  /etc/init.d/vmware service seems to run parallel with dkms build (because of vmnet dhcp service) and won't start because module build is not finished. 
After boot is complete you can restart the failed vmware service without a problem.

Question is: Is there any reason for the systemd target in dkms.service ? Can i change service file safely to ??:
[Unit] section:
Before=network-pre.target
Wants=network-pre.target

And what is the first safe run target in systemd for dkms ?

Best regards

**Comment by feuler** [comment]
Update:
This week i've built another dkms module (intel igb kernel driver update fix).
And after kernel upgrade + reboot with dkms bulding vmware-modules and intel igb driver, there was only a "lo" network interface. Somehow xorg+gdm was started while dkms modules where still compiling. That seemed to have triggered NetworkManager/network service getting started.
So, i also had to add "Before=graphical.target" to the dkms service so that networking gets initialized correctly after kernel upgrade reboot.

[Unit]
Before=network-pre.target graphical.target
Wants=network-pre.target

**Comment by yuzaipiaofei** [comment]
HI feuler:
Could you tell me which Suse release version you find this issue ?

**Comment by feuler** [comment]
Suse SLED 12 SP2 (and SP1)

**Comment by feuler** [comment]
And these are the two dkms modules vmware/intel igb:
[http://feuler.bplaced.net/vmware-modules-12-1.0.src.rpm](url)
[http://feuler.bplaced.net/vmware-modules-12-1.0.x86_64.rpm](url)
[http://feuler.bplaced.net/igb-dkms-5.3.5.4-1.0.src.rpm](url)
[http://feuler.bplaced.net/igb-dkms-5.3.5.4-1.0.x86_64.rpm](url)
