### ISSUE TITLE
dkms 3.0.4 service fail to start

### ISSUE THREAD

**Issue by tehungtseng1** [dell/dkms#228]
Hi our team when installing the latest dkms 3.0.4 and trying to start the service receive this error:

```
Jun 27 12:08:44 host systemd[1]: [/usr/lib/systemd/system/dkms.service:9] Executable path is not absolute, ignoring: dkms autoinstall --verbose --kernelver %v
Jun 27 12:08:44  systemd[1]: dkms.service lacks both ExecStart= and ExecStop= setting. Refusing.
```

Replacing the `/usr/lib/systemd/system/dkms.service` with 3.0.3 service file solved the issue.

systemd 219
CentOS Linux release 7.9.2009 (Core)

Thankful for any help.

Please tell me if you need any more information.

**Comment by schlagert** [comment]
Same problem here, using the absolute path `/usr/sbin/dkms` for the executable fixes the problem.

**Comment by scaronni** [comment]
Fixed in master.

**Comment by Tachi107** [comment]
My fault, sorry. Reading the [`systemd.service(5)`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Command%20lines) manual page I thought that I could use relative paths, but the feature was added in [systemd 239](https://github.com/systemd/systemd/blob/v239/NEWS#L154-L159), and Centos 7 only ships version 219.

Thanks to @scaronni for the fix :)
