### ISSUE TITLE
Unexpected sha512 call for non debian/ubuntu distro on 'unsupported distro'

### ISSUE THREAD

**Issue by SjonHortensius** [dell/dkms#231]
I noticed this error in my Arch Linux logs:
```
/usr/bin/dkms: line 1033: sha512: command not found
```

https://github.com/dell/dkms/blob/1e24a54acaa2e3a8aa6e8e24b21f47553370c4fe/dkms.in#L1033

This is most likely caused by `$sign_file` not being set, which is a bug imo. The sign-file block should not switch based on distro detection, but on feature detection (since `/usr/lib/modules/$kernelver/build/scripts/sign-file` is available on archlinux as well)

Additionally, the `eval $sign_file` should not be executed when `$sign_file` isn't set as it produces unexpected errors

**Comment by Iglu47** [comment]
same distro and error 
seems after https://github.com/dell/dkms/commit/3323033dfdc5f58afc303736f6b580bf62442ef7
`sudo pacman -U https://archive.archlinux.org/packages/d/dkms/dkms-3.0.3-1-any.pkg.tar.zst` helps as workaround
