### ISSUE TITLE
[README] project mailing list link in README 404s

### ISSUE THREAD

**Issue by amstewart** [dell/dkms#235]
[The link](https://github.com/dell/dkms/blob/a918925e8391305afdd58ec0f80fb780ca888206/README.md?plain=1#L172) for the `dkms-devel` mailing list in the project README either does not exist or is otherwise inaccessible from the public.

Both the [`dkms-devel` path](https://lists.us.dell.com/mailman/listinfo/dkms-devel) and the [`listinfo/` path](https://lists.us.dell.com/mailman/listinfo) (linked from Dell's lists.dell.com [homepage](https://lists.us.dell.com/)) return 404.

Developers would obviously prefer to access the mailing list.

![dell-listinfo-404](https://user-images.githubusercontent.com/10503146/178573513-f70aa357-f838-46c5-adbd-87ca5e155214.png)

Alternatively, is this mailing list no longer in-use? Is there some other community discussion mechanism?

**Comment by scaronni** [comment]
Removed the reference in the last commit. Mailing lists are long gone.

Unfortunately I have only commit access and nothing else to this repository, no one of the original project members is around and can grant me more access.

**Comment by amstewart** [comment]
Thanks for fixing.

>Unfortunately I have only commit access and nothing else to this repository, no one of the original project members is around and can grant me more access.

What does the maintenance structure for this repo look like? Is there any ownership from Dell?

**Comment by scaronni** [comment]
@johnahull are you an admin/owner of the repository and maybe the organization as well?

**Comment by johnahull** [comment]
Yes, i'm an organziation admin and can make whatever changes needed to the repository. I'll make you an admin

You're right, it probably makes sense to move it out of the Dell github. I'll discuss with some people internally and then update you.

**Comment by lerhaupt** [comment]
Thanks for your help John!

**Comment by scaronni** [comment]
> Yes, i'm an organziation admin and can make whatever changes needed to the repository. I'll make you an admin
> 
> You're right, it probably makes sense to move it out of the Dell github. I'll discuss with some people internally and then update you.

Thank you very much for your help! I can finally see all settings.
