### ISSUE TITLE
Unable to sign modules using PKCS#11 device

### ISSUE THREAD

**Issue by joamonwx** [dell/dkms#240]
Using eval to call sign_file unwraps the first level of quotes, argument variables should be passed in 2-levels of quotes to allow URIs to be passed as signing key `pkcs11:model=....`

Validation of signing key/cert pair as files further up, also breaks this.

See pull request #239

**Comment by scaronni** [comment]
Why did you close the pull request?

**Comment by joamonwx** [comment]
Unintentional, re-opened it.

**Comment by scaronni** [comment]
Pull request merged.
