### ISSUE TITLE
dkms recognized Ubuntu as Debian 

### ISSUE THREAD

**Issue by xuzhen** [dell/dkms#243]
Ubuntu's /etc/os-release file is like
```
NAME="Ubuntu"
VERSION="xx.yy (codename)"
ID=ubuntu
ID_LIKE=debian
...
```

But dkms prefers ID_LIKE to ID
https://github.com/dell/dkms/blob/49d647b6476d605feb10548e33fc3807415ec724/dkms.in#L317-L324

Then $running_distribution will be set to "debian"
https://github.com/dell/dkms/blob/49d647b6476d605feb10548e33fc3807415ec724/dkms.in#L2207

The $sign_file will be set to wrong path which is non-existent on Ubuntu
https://github.com/dell/dkms/blob/49d647b6476d605feb10548e33fc3807415ec724/dkms.in#L861-L873

**Comment by scaronni** [comment]
Thanks, I've added you as a contributor! So now we have someone actively using RedHat based systems, Debian based systems and Arch as contributors!
