### ISSUE TITLE
Where can I find a dkms-template?

### ISSUE THREAD

**Issue by trialley** [dell/dkms#248]
Hi! I am currently working on a dkms kernel module. It seems that there is no dkms module template, where can I get one?

**Comment by scaronni** [comment]
Just the `dkms.conf` file? Or the entire packaging step? If yes, for which distribution?

**Comment by evelikov** [comment]
We've tried having templates in-tree but they were badly outdated, thus got removed. I would suggest picking an up-to date dkms package from your distribution of choice and using that as a template. 

From a quick search here are two [v4l2loopback](https://salsa.debian.org/debian/v4l2loopback/-/tree/master/debian) and [r8168](https://salsa.debian.org/debian/r8168/-/tree/master/debian). Note I haven't tried either of them - Debian isn't my cup of tea.
