### ISSUE TITLE
DKMS modprobe_on_install overriden ?

### ISSUE THREAD

**Issue by th-hummel** [dell/dkms#287]
Hello,

I'm using `dkms-3.0.3-1.el8.noarch` on `RHEL 8.4 EUS x86_64` and it's working fine.
However, it seems that after the system `/etc/dkms/framework.conf` is sourced, some user-providable options variables are first emptied. Among them I can see `modprobe_on_install` which is set to `"true"` by default on my system but it then not used as overridden to no value. So basically this option in `framework.conf` has no effect.

`modprobe` auto launch after install does work if I provide the `--modprobe-on-install` or the ` --dkmsframework /etc/dkms/framework.conf` option though

Am I missing something obvious ?

Thanks for your help

--
Thomas HUMMEL

**Comment by scaronni** [comment]
Can you please try again with the latest version? https://koji.fedoraproject.org/koji/buildinfo?buildID=2081498

I haven't pushed it to the testing updates. Thanks.

**Comment by th-hummel** [comment]
> 

Hello,

I tested with your provided version and it does not change the behavior.
Looking at code, it still seems to me that `framwork.conf` is sourced and *then* `modprobe_on_install` is emptied (so if it not given as a command line option, it will still be empty)

Thanks for your help

-- 
TH

**Comment by scaronni** [comment]
Gotcha, sorry for not understanding immediately.

The commit is in master, I'm rebuilding the package with the patch applied until a new release comes out. The new package is `3.0.9-2`:

https://koji.fedoraproject.org/koji/packageinfo?packageID=1605

**Comment by th-hummel** [comment]
Hello,

actually there was a misunderstanding on my part too :  I did not realize that variable *values* such as `modprobe_on_install` or `AUTOINSTALL` did not matter (only if there were empty strings or not)
Seeing in some `dkms.conf` files, for instance `AUTOINSTALL="yes"` misguided me.
Seeing code using `[[ $var ]]` like constucts make me get it.

Hopefully and oddly enough (by chance), this did not change the need of the fix ;-)

Thanks again

-- 
TH
