### ISSUE TITLE
module version check causes WARNING build vs. install

### ISSUE THREAD

**Issue by celane** [dell/dkms#290]
The changed module version code in v3.0.9 returns mismatched versions on the same file.  (Alma 8.6, but there are reports from other  distros with the same problem).

The source of the problem:
get_module_verinfo() 
   echo ""  (since there is no 'version' line in modinfo)
   echo "A8869EFB63B2CF973E19263"   (srcversion hex string)

compare_module_version reads these two lines into an array for each file, but the test:
if [[ ! "$ver1" ]] || [[ ! "$ver2" ]]; then
        echo "?"
        return 1
    fi

echos "?" with return status of "no match" , because the  [[ ! "$ver1" ]]  test results in 'true' for the blank first entry in the array.

Suggested fix to test: 
if [[  "${#ver1[\*]}" == 0 ]] || [[  "${#ver2[\*]}" == 0 ]]; then

that checks that the arrays have some entries.

**Comment by xuzhen** [comment]
I've opened a pull request for this. But all modules should use `MODULE_VERSION()` in their source code to set a version IMHO

**Comment by celane** [comment]
"But all modules should use MODULE_VERSION() in their source code to set a version IMHO"

Strong agreement. 
Unfortunately, spot checking on Alma 8.6 and Fedora 35 didn't turn up *any* installed modules that had a 'Version' set. 
I ran into this problem of modules not having a way to check their version, years ago, and it was frustrating. 

Time to poke at module code, to get a MODULE_VERSION() added.
