### ISSUE TITLE
DKMS Issue when module has to be replaced

### ISSUE THREAD

**Issue by kodatarule** [dell/dkms#296]
Hello,
Firstly after this merge request https://github.com/dell/dkms/pull/291 I can no longer install the package new-lg4ff-dkms-git from the aur repository.. it requires me to run --force OR way more simpler to just use previous dkms version.
While that merge request is quite beneficial, this could be considered as a regression + way to workaround it(ex. make it force the install if it doesn't want to be replaced + give a warning to the user).

EDIT: two examples the previous DKMS version and the new one:
New:
![image](https://user-images.githubusercontent.com/65848953/214349927-f945b6f2-d985-470f-b241-64401bdd38e4.png)

Old:
![image](https://user-images.githubusercontent.com/65848953/214349972-15e2165b-c65e-41f3-8376-4e9dce01e5f4.png)

**Comment by xuzhen** [comment]
Could you test this patch https://github.com/xuzhen/dkms/commit/ae2ef4028105b84c5610ffa9971193ff886ef763 ?

**Comment by kodatarule** [comment]
Yes that seemed to have worked! Thanks!
