### ISSUE TITLE
dkms ignores --kernelsourcedir if /lib/modules/$kernel_version exists

### ISSUE THREAD

**Issue by Glandos** [dell/dkms#30]
Hi,
In order to build one module, I need to have the complete kernel source tree.
I'm trying to use DKMS on CentOS7 to build it.

However, using the option `--kernelsourcedir` seems to have no effect. And indeed, since kernel headers are already installed in `/usr/src` and linked into `/lib/modules/<kernel_version>/build`, the `dkms build` uses it instead of my custom parameter.

Is there anything I missed from the documentation?

**Comment by yuzaipiaofei** [comment]
@Glandos 
I think you need dkms/dkms_framework.conf to set your own environment for debuging .

**Comment by yuzaipiaofei** [comment]
Close the question.
Feel free to comment when you still have questions.
