### ISSUE TITLE
NO_WEAK_MODULES removed from Man Why ?

### ISSUE THREAD

**Issue by enigma131** [dell/dkms#304]
I don't understand why NO_WEAK_MODULES is removed from Man page (in dkms.conf section)
It is still necessary for Redhat systems (including Fedora, I use boths)
Can it be restored ?

**Comment by evelikov** [comment]
The code is still there, so it's a mistake on my end. Feel free to open a MR, alternatively I'll try to get to it over the weekend.

**Comment by enigma131** [comment]
Thanks for the commit.

**Comment by evelikov** [comment]
You're welcome. Sorry for dropping the documentation in the first place :sweat_smile:
