### ISSUE TITLE
PACKAGE_VERSION built dynamically

### ISSUE THREAD

**Issue by cyring** [dell/dkms#336]
Hello,

Can `PACKAGE_VERSION` be sourced from an include file or from inlined scripting commands ?

Like:
```
PACKAGE_VERSION="$(grep major_minor version.h¦cut somewhere)"
```

Where `version.h`
```c
#define major_minor 1.23
```

**Comment by evelikov** [comment]
Looking at this example makes me quite uncomfortable. Surely you can add a simple sed command to your Makefile to properly set the `PACKAGE_VERSION` right?

A while ago we removed the majority of places where shell can be abused. Considering that dkms is run with root privileges (most of the time), I don't think we want to allow this.

Sorry for the bad news. If you have a repo, I am more than happy to send a patch demonstrating the sed/Makefile suggestion above.
