### ISSUE TITLE
Ubuntu 22.04 VM broke

### ISSUE THREAD

**Issue by evelikov** [dell/dkms#405]
Recently the CI broke in a somewhat odd manner:

 - latest [working job](https://github.com/dell/dkms/actions/runs/8056783845/job/22006586247) shows:
```
Using kernel 6.2.0-1019-azure/x86_64
Checking module compression ...
config: CONFIG_MODULE_COMPRESS_NONE=y
files: /lib/modules/6.2.0-1019-azure/kernel/crypto/af_alg.ko
Expected extension: (none)
```
 - comparing to the [first broken one](https://github.com/dell/dkms/actions/runs/8148212410/job/22270586394):
```
Using kernel 6.5.0-1015-azure/x86_64
Checking module compression ...
config: CONFIG_MODULE_COMPRESS_ZSTD=y
files: /lib/modules/6.5.0-1015-azure/kernel/crypto/af_alg.ko
Expected extension: .zst
```

Comparing these with the container runs (22.04 and 23.10 respectively) which remain working fine.

Ubuntu 22.04
```
Found kernel 5.15.0-97-generic
Module search paths
/etc/depmod.d/ubuntu.conf:search updates ubuntu built-in
Using kernel 5.15.0-97-generic/x86_64
Checking module compression ...
config: CONFIG_MODULE_COMPRESS_NONE=y
files: /lib/modules/5.15.0-97-generic/kernel/fs/nfs/nfsv3.ko
Expected extension: (none)
```

Ubuntu 23.10
```
Found kernel 6.5.0-21-generic
Module search paths
/etc/depmod.d/ubuntu.conf:search updates ubuntu built-in
Using kernel 6.5.0-21-generic/x86_64
Checking module compression ...
config: CONFIG_MODULE_COMPRESS_ZSTD=y
files: /lib/modules/6.5.0-21-generic/kernel/fs/nfs/nfsv3.ko.zst
Expected extension: .zst
```

It seems like the `azure` flavour of the `6.5.0` kernel is using zstd kconfig yet the modules are actually uncompressed.
@xnox the current state seems broken. Any chance someone in the Canonical/Ubuntu team can fix this?

Thanks in advance

**Comment by xuzhen** [comment]
The `Makefile.modinst` file was modified in Ubuntu. 
```
--- linux-azure-6.5.0.orig/scripts/Makefile.modinst
+++ linux-azure-6.5.0/scripts/Makefile.modinst
@@ -24,7 +24,9 @@
 suffix-y				:=
 suffix-$(CONFIG_MODULE_COMPRESS_GZIP)	:= .gz
 suffix-$(CONFIG_MODULE_COMPRESS_XZ)	:= .xz
-suffix-$(CONFIG_MODULE_COMPRESS_ZSTD)	:= .zst
+## UBUNTU: Support, but do not require zstd compressed modules
+# Many external dkms and signing rely on uncompressed modules
+# suffix-$(CONFIG_MODULE_COMPRESS_ZSTD)	:= .zst
 
 modules := $(patsubst $(extmod_prefix)%.o, $(dst)/%.ko$(suffix-y), $(modules))
 ```
from http://ftp.ubuntu.com/ubuntu/pool/main/l/linux-azure/linux-azure_6.5.0-1018.19.diff.gz

FYI:
1. https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/commit/?h=Ubuntu-hwe-6.5-6.5.0-14.14_22.04.1&id=21f3ac7412644fb59a13db2e3adbb8a38cba9923
2. https://bugs.launchpad.net/bugs/2045593

**Comment by xuzhen** [comment]
﻿It looks like only Ubuntu 22.04 (Jammy) with kernel version 6.5 or later will have this issue.
