### ISSUE TITLE
Version and Date not up to date in manpage

### ISSUE THREAD

**Issue by mseeber** [dell/dkms#41]
I noticed that the date and version number in the manpage dkms.8 are not updated with the release version of dkms.

Is there sense in inserting the current date/version in the tarball/install targets in the Makefile? If so I could provide a patch later.

**Comment by superm1** [comment]
I think that's a great idea at least with the release version.  I'd argue the date should just be removed though.  It doesn't really offer any value.

**Comment by scaronni** [comment]
Patch here, if that is ok for you I can merge it: https://github.com/dell/dkms/pull/45

**Comment by yuzaipiaofei** [comment]
@scaronni 
As Mario said .the date dose not have much value change.
But i merge your patch now.  thanks for the improvement work.
I would like to see if the patch can work for the next release.

**Comment by yuzaipiaofei** [comment]
If you do not have new issue for this .
I would close this issue now.
