### ISSUE TITLE
Ship `kernel-install` snippet to `/usr/` instead of `/etc/`

### ISSUE THREAD

**Issue by behrmann** [dell/dkms#430]
Currently the `40-dkms.install` snippet is shipped to `$(DESTDIR)$(KCONF)/install.d/40-dkms.install`, but `KCONF` defaults to `/etc/kernel`. Unlike the `postinst.d` and `prerm.d` machinery `kernel-install` supports to have these files shipped in `/usr/`, which allows administrators to add superseding configuration in `/etc/`. It would therefore be helpful if the file could be shipped in `/usr/` instead.

**Comment by bluca** [comment]
https://github.com/dell/dkms/pull/431

**Comment by bluca** [comment]
related to https://github.com/dell/dkms/issues/343
