### ISSUE TITLE
Regression in 3.1.0

### ISSUE THREAD

**Issue by FlyingWaffleDev** [dell/dkms#447]
The commit fee652112a947e98360e236b29ab8d3bc70da9ac  (#440) introduced a failure on non-Debian systems by removing the log_action_msg and log_daemon_msg function stubs in dkms_autoinstaller while leaving calls to these functions in the code.

This regression was specifically encountered running kernel builds on Gentoo.

**Comment by scaronni** [comment]
Thanks for reporting.

Actually, the correct thing to avoid distribution specific code, is to remove the `log_action_msg` calls with a simple `echo` like the rest of the scripts.
