### ISSUE TITLE
/usr/lib/dkms/common.postinst does not exist since 3.1.3 on Fedora Rawhide and OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by SergeiShtepa** [dell/dkms#465]
Hi! 

Since dkms v3.1.3 when installing modules that used the common.postinst script, they cannot execute the %post section.
For example [issue for openZFS](https://github.com/openzfs/zfs/issues/15175).
The blksnap module has the same [issue](https://forums.veeam.com/veeam-agents-for-linux-mac-aix-solaris-f41/blksnap-agent-6-for-linux-fails-to-build-on-current-opensuse-tumbleweed-t85166.html).

I thought this script was recommended for use.
For example, [this article](https://nilrt-docs.ni.com/opkg/dkms_opkg.html#postinst) (first one I found), advises to use this script.

It seems to me that it would be great to keep the existing dkms modules working.
If you find this impractical, I would like to get recommendations on best practice.

Thanks!

**Comment by scaronni** [comment]
Hi, the script has not been deleted, just not installed anymore with the `install-redhat` target. It's still there for the `install-debian` target as I know it's pretty entangled in some Debian pacakges.

I can add it back, but to be honest I find it a bit redundant. The same that the script does can be summarized with these lines (https://github.com/negativo17/dkms-nvidia/blob/master/dkms-nvidia.spec#L58-L66):

```
%post
dkms add -m %{dkms_name} -v %{version} -q --rpm_safe_upgrade || :
# Rebuild and make available for the currently running kernel:
dkms build -m %{dkms_name} -v %{version} -q || :
dkms install -m %{dkms_name} -v %{version} -q --force || :

%preun
# Remove all versions from DKMS registry:
dkms remove -m %{dkms_name} -v %{version} -q --all --rpm_safe_upgrade || :
```

If there's the need I can readd it to the install target, but I find pretty redundant.

**Comment by SergeiShtepa** [comment]
Hi!
Thanks for the reply and thanks for the example of best practices.
I will apply them in my module.
The issue can be closed.

P.S.: Perhaps the common.postinst script is really not suitable for the rhel-based system and looks redundant.
But maybe it would be great to keep compatibility and return common.postinst, but with a different, simpler content?

**Comment by scaronni** [comment]
> P.S.: Perhaps the common.postinst script is really not suitable for the rhel-based system and looks redundant. But maybe it would be great to keep compatibility and return common.postinst, but with a different, simpler content?

Yes, could be. I personally fail to see how. If you have time, please propose something with a merge request. Thanks.

**Comment by abhinavsood** [comment]
This breaks the installation of NVidia graphics driver on Red Hat Enterprise Linux 9. In my case, I can no longer install the Nvidia Grid Graphics Driver from the RPM package `nvidia-linux-grid-535-535.183.06-1.rpm`.

```sh
# rpm -iv ./nvidia-linux-grid-535-535.183.06-1.x86_64.rpm
```

```
Verifying packages...
Preparing packages...
nvidia-linux-grid-535-1:535.183.06-1.x86_64
Running Post-install scripts
/usr/lib/nvidia/postinst: line 8: /usr/lib/dkms/common.postinst: No such file or directory
```

**Comment by SergeiShtepa** [comment]
Check it out - [this patch](https://github.com/dell/dkms/commit/29f14df8688860f4699ad3cda1c7a2916ad3ba12) should solve the problem.

**Comment by scaronni** [comment]
That's not needed at all, I've readded the file to 3.1.4 even if not required for building modules on Red Hat.

@abhinavsood I'll check internally who assembles the Nvidia Linux Grid package.
