### ISSUE TITLE
Error in dkms mkdeb documentation

### ISSUE THREAD

**Issue by martingalvan** [dell/dkms#54]
The man page for dkms says the following of dkms mkdeb:

`It uses a template debian directory found in  /etc/dkms/template-dkms-mkdeb as the basis for the package. Alternatively, if DKMS finds a file called /usr/src/<module>-<module-version>/<module>-dkms-mkdeb it will use that folder instead.`

That seems to be wrong. The dkms script actually uses `"$dkms_tree/$module/$module_version/source/$module-dkms-mk${create_type}"`. The `${module}-dkms-mkdeb dir` should be placed in the source dir (i.e. what gets passed to `dkms build --sourcetree`).

I presume the same applies for all the other dkms mk* variants.

**Comment by scaronni** [comment]
Distribution specific packaging was severely broken for most distributions and has been dropped in the latest release.
