### ISSUE TITLE
dkms mkrpm: post_remove scripts are always non-executable

### ISSUE THREAD

**Issue by martingalvan** [dell/dkms#55]
Symptoms are the same as for https://github.com/dell/dkms/issues/53. This issue isn't present in DKMS 2.4, but is in 2.6.

**Comment by martingalvan** [comment]
Is anyone looking at this?

**Comment by martingalvan** [comment]
Pinging this again. This bug still exists, is anyone looking at it?

**Comment by scaronni** [comment]
Distribution specific packaging was severely broken for most distributions and has been dropped in the latest release.
