### ISSUE TITLE
DKMS release schedule?

### ISSUE THREAD

**Issue by jfloret** [dell/dkms#6]
Hello,

The latest dkms release (v2.2.0.3) is 5 years old, and a good number of bug fixes and new features
have been integrated in the master branch since this tag.
Is it planned to tag a new dkms release?

Regards,
Julien

**Comment by jared-dominguez** [comment]
Hi there,

Yes, it's something I'm meaning to do. Feel free to poke me if it doesn't happen in the next two weeks.

--Jared

**Comment by jared-dominguez** [comment]
DKMS 2.3 is tagged
