### ISSUE TITLE
Installing Device Tree Overlays using DKMS

### ISSUE THREAD

**Issue by taudac** [dell/dkms#7]
Hi all,

apart from kernel modules, I would like to install device tree overlays using DKMS.

The key differences here are:
(1) file extension, *.dtbo instead of *.ko
(2) installation destination, for example, /boot/overlays/ instead of /lib/modules/<kernelversion>/kernel/

What would be a clean way to do it?

Any hints are highly appreciated.

Best regards
Sergej

**Comment by yuzaipiaofei** [comment]
It's a good idea for dkms feature extending  . 
Device tree built with dkms  will be considerd in the future development work .

**Comment by yuzaipiaofei** [comment]
I would like to close the issue now .
if you have more questions.  Please feel free to open it.
