### ISSUE TITLE
module signing for kernel_lockdown

### ISSUE THREAD

**Issue by atar-axis** [dell/dkms#72]
Hi there, thank you for DKMS, I absolutely appreciate that tool!

Have you ever thought about an automated way for signing DKMS modules?
Like described here: 
https://gist.github.com/dop3j0e/2a9e2dddca982c4f679552fc1ebb18df

Cheers, Flo

**Comment by superm1** [comment]
Patches welcome for this definitely, but I think it's a great idea.

**Comment by xuzhen** [comment]
I implemented a simple module signing mechanism, see https://github.com/dell/dkms/pull/87

**Comment by yuzaipiaofei** [comment]
@xuzhen 
I have merged this patch.
Thanks

**Comment by raul-klg** [comment]
If the feature is already merged, is there any reason to keep this issue opened?
