### ISSUE TITLE
`dkms mkdeb` does not include binaries

### ISSUE THREAD

**Issue by npf** [dell/dkms#74]
Hi,
`dkms mkdeb` seems to not include the .ko module files (binaries).
Either this is a bug, or preferably this is just the good way to go, but usage and man page should be fixed so that --source-only is de facto, an --binaries-only is not an option.

Also note that if `mkdeb` could actually produce a deb with binaries inside, it should not be `_all.deb`, but an architecture specific deb package (e.g. `amd64.deb`).

My proposal would be to take the approach chosen in Debian's dkms version (fork):
- have a `mkdeb ` command to create the dkms source package, `all.deb`
- have a `mkbmdeb` command to create the dkms binary modules package (arch specific package)
This means merging Debian's patches for `mkbmdeb`, and fixing `mkdeb` usage.
See: https://salsa.debian.org/debian/dkms/blob/master/debian/patches/0004-mkbmdeb-support-for-lean-binary-package-with-only-th.patch

This is something discussed in Debian bug tracking system here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=832558#100

**Comment by GoPerry** [comment]
patches merge,close the issue.
Thanks for the codes contribution.
please feel free to reopen the issue if you still have any questions for this.
